### ISSUE TITLE
Need to fix bug in custom_combined_rubias_output()

### ISSUE THREAD

**Issue by awbarclay** [commfish/GCLr#103] opened 2024-12-12 00:12 UTC
When resummarizing the rubias output to finer-scale groups, I got the following error: "object 'collection_trace' not found"

I traced the error to lines 209 and 212, where the function calls an object called "collection_trace", but it is never created in the function.  Replacing collection_trace with repunit_trace should fix the issue.

**Comment by krshedd** [comment] 2024-12-12 00:25
@awbarclay just took a quick look and it looks like the issue is line 191 where the `pblapply` is assigning to `repunit_trace` when it should be `collection_trace`. However, I haven't tested to see if that solves your issue.

**Comment by awbarclay** [comment] 2024-12-12 00:29
@krshedd Yes, the issue can be fixed either way.  I already tested it, so I know it will works.  I'll try to do a hot fix tomorrow.

**Closed** 2024-12-12 18:34 UTC
Labels: bug
